### ISSUE TITLE
GPU-mux on docker

### ISSUE THREAD

**Issue by MikeChenfu** [google/gpu-mux#5]
Is there any way to run gPU-mux on docker container which built in a remote server?  Thanks.

**Comment by david-berthelot** [comment]
I don't have experience with docker. Given that GPU-Mux is on GitHub and can also be installed with `pip` I think you have better chances to get an answer by reaching out to these communities to ask your question (or may be stackoverflow).

**Comment by MikeChenfu** [comment]
Thanks @david-berthelot. I'll do it and  try it on docker container.
